Коноплев Григорий Дмитриевич, Б05-206, контест 1, задача H, посылка 70363414
Gri-hub/AlgoYearCourse pull request #2
Opened 2022-10-13 19:43 UTC by Gri-hub

2022-10-14 14:26 UTC, VladislavHacker requested changes

2022-10-14 14:26 UTC, VladislavHacker commented on taskH.cpp
> +int main() {
надо тож на функции разбить
и для размеров массивов и индексов используй size_t

2022-10-31 19:40 UTC, Gri-hub commented
Переделал

2022-11-04 00:26 UTC, VladislavHacker approved these changes

2022-12-07 08:49 UTC, merged