Коноплев Григорий Дмитриевич, Б05-206, контест 1, задача B, посылка 70539542
Gri-hub/AlgoYearCourse pull request #3
Opened 2022-10-13 19:45 UTC by Gri-hub

2022-10-14 14:22 UTC, VladislavHacker requested changes

2022-10-14 14:22 UTC, VladislavHacker commented on taskB.cpp
> +  int min = kMaxInt;
std::numeric_limits<int>::max()

2022-10-14 14:22 UTC, VladislavHacker commented on taskB.cpp
> +  int array_size;
size_t

2022-10-14 14:22 UTC, VladislavHacker commented on taskB.cpp
> +
опять весь код в main)
разбей на функции как и для предыдущей задачи

2022-10-31 19:38 UTC, Gri-hub commented
Переделал

2022-11-04 00:24 UTC, VladislavHacker approved these changes

2022-12-07 09:00 UTC, closed without merging