Коноплев Григорий Дмитриевич, Б05-206, контест 1, задача A, посылка 70539321
Gri-hub/AlgoYearCourse pull request #7
Opened 2022-10-13 20:12 UTC by Gri-hub

2022-10-14 14:20 UTC, VladislavHacker requested changes

2022-10-14 14:20 UTC, VladislavHacker commented on taskA.cpp
> +  int array_length;
size_t

2022-10-14 14:20 UTC, VTroyanGolovyan commented on taskA.cpp
> +  long left_boundary = 0;
size_t

2022-10-14 14:20 UTC, VTroyanGolovyan commented on taskA.cpp
> +int main() {
разбей код на функции
функция для чтения
для обработки запросов
для вывода ответа

2022-10-31 19:16 UTC, Gri-hub commented
Переделал

2022-11-04 00:25 UTC, VladislavHacker approved these changes

2022-12-07 09:32 UTC, merged